import { ROLES } from '../roles';

export const ROLE_PERMISSIONS = {
  [ROLES.SUPER_ADMIN]: [
    { id: 'dashboard', label: 'Dashboard', icon: 'dashboard', path: '/super-admin' },
    { id: 'users', label: 'All Users', icon: 'users', section: 'User Management' },
    { id: 'super-admins', label: 'Super Admins', icon: 'user-check' },
    { id: 'regional-managers', label: 'Regional Managers', icon: 'user-check' },
    { id: 'branch-heads', label: 'Branch Heads', icon: 'user-check' },
    { id: 'technicians', label: 'Technicians', icon: 'wrench' },
    { id: 'salespersons', label: 'Salespersons', icon: 'users' },
    { id: 'zones', label: 'Zones', icon: 'globe', section: 'Territories' },
    { id: 'branches', label: 'Branches', icon: 'building' },
    { id: 'customers', label: 'Customers', icon: 'customer-list', section: 'Data' },
    { id: 'visits', label: 'Visits', icon: 'clipboard' },
    { id: 'leads', label: 'Leads', icon: 'flame' },
    { id: 'follow-ups', label: 'Follow-ups', icon: 'clock' },
    { id: 'reports', label: 'Reports', icon: 'file-text', section: 'Analytics' },
    { id: 'notifications', label: 'Notifications', icon: 'bell' },
    { id: 'settings', label: 'Settings', icon: 'settings' },
  ],
  [ROLES.REGIONAL_MANAGER]: [
    { id: 'dashboard', label: 'Dashboard', icon: 'dashboard', path: '/regional-manager' },
    { id: 'users', label: 'All Zone Users', icon: 'users', section: 'User Management' },
    { id: 'branch-heads', label: 'Branch Heads', icon: 'user-check' },
    { id: 'technicians', label: 'Technicians', icon: 'wrench' },
    { id: 'salespersons', label: 'Salespersons', icon: 'users' },
    { id: 'branches', label: 'Branches', icon: 'building', section: 'Territory' },
    { id: 'customers', label: 'Customers', icon: 'customer-list', section: 'Data' },
    { id: 'visits', label: 'Visits', icon: 'clipboard' },
    { id: 'leads', label: 'Leads', icon: 'flame' },
    { id: 'follow-ups', label: 'Follow-ups', icon: 'clock' },
    { id: 'reports', label: 'Reports', icon: 'file-text', section: 'Analytics' },
    { id: 'notifications', label: 'Notifications', icon: 'bell' },
    { id: 'settings', label: 'Settings', icon: 'settings' },
  ],
  [ROLES.BRANCH_HEAD]: [
    { id: 'dashboard', label: 'Dashboard', icon: 'dashboard', path: '/branch-head' },
    { id: 'users', label: 'All Branch Staff', icon: 'users', section: 'User Management' },
    { id: 'technicians', label: 'Technicians', icon: 'wrench' },
    { id: 'salespersons', label: 'Salespersons', icon: 'users' },
    { id: 'customers', label: 'Customers', icon: 'customer-list', section: 'Branch Operations' },
    { id: 'visits', label: 'Visits', icon: 'clipboard', section: 'Activities' },
    { id: 'leads', label: 'Leads', icon: 'flame' },
    { id: 'follow-ups', label: 'Follow-ups', icon: 'clock' },
    { id: 'reports', label: 'Reports', icon: 'file-text', section: 'Analytics' },
    { id: 'notifications', label: 'Notifications', icon: 'bell' },
    { id: 'settings', label: 'Settings', icon: 'settings' },
  ],
  [ROLES.TECHNICIAN]: [
    { id: 'dashboard', label: 'Dashboard', icon: 'dashboard', path: '/technician' },
    { id: 'my-visits', label: 'My Visits', icon: 'clipboard', section: 'Field Work' },
    { id: 'customers', label: 'Customers', icon: 'customer-list' },
    { id: 'todays-tasks', label: 'Today\'s Tasks', icon: 'check-circle' },
    { id: 'follow-ups', label: 'Follow-ups', icon: 'clock' },
    { id: 'notifications', label: 'Notifications', icon: 'bell', section: 'System' },
  ],
  [ROLES.SALESPERSON]: [
    { id: 'dashboard', label: 'Dashboard', icon: 'dashboard', path: '/salesperson' },
    { id: 'my-customers', label: 'My Customers', icon: 'customer-list', section: 'Sales Activity' },
    { id: 'customer-visits', label: 'Customer Visits', icon: 'clipboard' },
    { id: 'leads', label: 'Leads', icon: 'flame' },
    { id: 'todays-followups', label: 'Today\'s Follow-ups', icon: 'clock' },
    { id: 'notifications', label: 'Notifications', icon: 'bell', section: 'System' },
  ],
};
